name: Basic Worflow Trigger Awareness
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      
      - run: |
         echo "This is a dummy job to demonstrate workflow triggers based on file changes."
         ls -la
         echo "Done"